// Single, app-wide Supabase entry point.
// All app code MUST import { supabase } from "@/lib/supabase" — never from
// "@/integrations/supabase/client" directly. That generated file is
// regenerated by Lovable on every edit; routing imports through here means
// switching to a self-hosted Supabase later only requires changing this file.
export { supabase } from "@/integrations/supabase/client";
