/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicTriageSentenceRouteImport } from './routes/api/public/triage-sentence'
import { Route as ApiPublicNotifyFeedbackRouteImport } from './routes/api/public/notify-feedback'
import { Route as ApiPublicAnalyzeSentenceRouteImport } from './routes/api/public/analyze-sentence'

const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTriageSentenceRoute = ApiPublicTriageSentenceRouteImport.update({
  id: '/api/public/triage-sentence',
  path: '/api/public/triage-sentence',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicNotifyFeedbackRoute = ApiPublicNotifyFeedbackRouteImport.update({
  id: '/api/public/notify-feedback',
  path: '/api/public/notify-feedback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAnalyzeSentenceRoute =
  ApiPublicAnalyzeSentenceRouteImport.update({
    id: '/api/public/analyze-sentence',
    path: '/api/public/analyze-sentence',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/api/public/analyze-sentence': typeof ApiPublicAnalyzeSentenceRoute
  '/api/public/notify-feedback': typeof ApiPublicNotifyFeedbackRoute
  '/api/public/triage-sentence': typeof ApiPublicTriageSentenceRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/api/public/analyze-sentence': typeof ApiPublicAnalyzeSentenceRoute
  '/api/public/notify-feedback': typeof ApiPublicNotifyFeedbackRoute
  '/api/public/triage-sentence': typeof ApiPublicTriageSentenceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/api/public/analyze-sentence': typeof ApiPublicAnalyzeSentenceRoute
  '/api/public/notify-feedback': typeof ApiPublicNotifyFeedbackRoute
  '/api/public/triage-sentence': typeof ApiPublicTriageSentenceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/api/public/analyze-sentence'
    | '/api/public/notify-feedback'
    | '/api/public/triage-sentence'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/api/public/analyze-sentence'
    | '/api/public/notify-feedback'
    | '/api/public/triage-sentence'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/api/public/analyze-sentence'
    | '/api/public/notify-feedback'
    | '/api/public/triage-sentence'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  ApiPublicAnalyzeSentenceRoute: typeof ApiPublicAnalyzeSentenceRoute
  ApiPublicNotifyFeedbackRoute: typeof ApiPublicNotifyFeedbackRoute
  ApiPublicTriageSentenceRoute: typeof ApiPublicTriageSentenceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/triage-sentence': {
      id: '/api/public/triage-sentence'
      path: '/api/public/triage-sentence'
      fullPath: '/api/public/triage-sentence'
      preLoaderRoute: typeof ApiPublicTriageSentenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/notify-feedback': {
      id: '/api/public/notify-feedback'
      path: '/api/public/notify-feedback'
      fullPath: '/api/public/notify-feedback'
      preLoaderRoute: typeof ApiPublicNotifyFeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/analyze-sentence': {
      id: '/api/public/analyze-sentence'
      path: '/api/public/analyze-sentence'
      fullPath: '/api/public/analyze-sentence'
      preLoaderRoute: typeof ApiPublicAnalyzeSentenceRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  ApiPublicAnalyzeSentenceRoute: ApiPublicAnalyzeSentenceRoute,
  ApiPublicNotifyFeedbackRoute: ApiPublicNotifyFeedbackRoute,
  ApiPublicTriageSentenceRoute: ApiPublicTriageSentenceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
